#!/bin/bash

echo "$@" argument: "$#"


# del ruletraffic
#6           0 (Src: 192.168.1.0/24) && (qname in youku.com.)     to pool bii

if [ $# -ne 3 ]; then
    echo "usage: $0 acls poolname"
    echo "example: $0 192.168.0.0/24,192.168.1.0/24 youku.com,qq.com edu"
    echo "example: $0 192.168.0.0/24 qq.com edu"
    exit 1
fi

ACLS="$1"
DOMAINS="$2"
POOL="$3"
CONF="/etc/dnsdist/dnsdist.conf"

for acl in $(echo $ACLS|sed 's/,/ /'); do
    for domain in $(echo $DOMAINS|sed 's/,/ /'); do
        num=$(dnsdist -c -e "showRules()" |grep "(Src: $acl) && (qname in $domain.)\s* to pool $POOL"|awk '{print $1}')
        for n in $num; do
            if [ -z "$n" ]; then
                :
            else
                if [ "$n" -ge 0 ]; then
                    dnsdist -c -e "rmRule($n)"
                fi
            fi
        done

        # del a ruleview in /etc/dnsdist.conf
        sed -i '\#^addAction(AndRule({makeRule("'$acl'"), makeRule("'$domain'")}), PoolAction("'$POOL'"))#d' "$CONF"
    done
done
