#!/bin/bash

echo "$@" argument: "$#"
exit
#
# 更新pool 属性
#   * servers, policy, cache
#

if [ $# -ne 4 ]; then
    echo "usage: $0 name servers policy cache"
    echo "example: $0 edu edu-rec1,edu-rec2 whashed edu"
    exit 1
fi

NAME="$1"
SERVERS="$2"
POLICY="$3"
CACHE="$4"

CONF="/etc/dnsdist/dnsdist.conf"

#dnsdist -c -e "showServers()" >/tmp/pools.log
#DIST_SERVERS="$(awk '{if ($NF == "'$NAME'") print $1 }' /tmp/pools.log)"

# update server, add or delete
#for s in $(echo $SERVERS|sed 's/,/ /g'); do
#    SERVER_ID="$(dnsdist -c -e "showServers()" |grep -w "$s" |awk '{print $1}')"
#    dnsdist -c -e "getServer($SERVER_ID):addPool('$NAME')"
#    
#
#    # set server's pool in /etc/dnsdist.conf
#    if egrep '^\s*newServer\({name="'$s'"' "$CONF">/dev/null; then
#        sed -r -i 's/newServer\(\{name="'$s'"''(.*)\}\)/newServer\(\{name="'$s'"''\1, pool="'$NAME'"\}\)/' $CONF
#    fi
#done

# set policy and cache
dnsdist -c -e "setPoolServerPolicy($POLICY, '$NAME')"
dnsdist -c -e "getPool('$NAME'):setCache($CACHE)"

# set policy in /etc/dnsdist/dnsdist.conf
#if egrep '^\s*setPoolServerPolicy\((.*), '\'$NAME\'\) "$CONF">/dev/null; then
sed -r -i 's/setPoolServerPolicy\((.*), '"'$NAME'"'\)/SetPoolServerPolicy\('$POLICY', '"'$NAME'"'\)/' $CONF
#fi

# set cache in /etc/dnsdist/dnsdist.conf
sed -r -i 's/getPool\('"'$NAME'"'\):setCache\((.*)\)/getPool\('"'$NAME'"'\):setCache('$CACHE'\)/' $CONF
